### ISSUE TITLE
[7281] SPIKE: Post-ITT reform – don't split org in 2 if they lose accreditation 

### ISSUE THREAD

**Issue by stevehook** [DFE-Digital/register-trainee-teachers#4447]
## Background
When users for HEI lead partners log in to Register they will need to pick  whether they want to view trainees for their regular HEI provider or their new  lead partner. This is similar to what happens when users are associated with multiple providers or lead schools. It is somewhat awkward UX and as such we are looking for alternative solutions.

## Changes proposed
I've focused on the idea of having users logged in with multiple organisations in the same session. If we can achieve this it would mean that individual users have an optional association with multiple organisations. This would allow users  to see trainees for all organisations that they belong to without having to log out and log back in again.

## What are the benefits of having users logged in with multiple organisations?
Users can see all of their trainees in one place. It will simplify the UI somewhat as we would no longer need a form to select from multiple organisations. It will be less confusing for anyone that has to juggle multiple organisations.

## What are the potential downsides of having users logged in with multiple organisations?
There is some complexity added to the logic used to construct the trainee queries, authorisation rules (Pundit policies) and the UI. I think this is manageable.

## Outline implementation plan
- [ ] I think we'd probably want to have a feature flag for this piece of work so that it can be deployed in chunks and activated when ready. Slightly less likely but a feature flag would allow us to revert the functionality if it causes issues.
- [ ] Update [`UserWithOrganisationContext`](https://github.com/DFE-Digital/register-trainee-teachers/blob/main/app/lib/user_with_organisation_context.rb) session state wrapper to handle multiple organisations at once.
- [ ] Alter any logic that redirects to the organisation selection page if you've just logged in with multiple organisations.
- [ ] Update the [`TraineePolicy`](https://github.com/DFE-Digital/register-trainee-teachers/blob/main/app/policies/trainee_policy.rb) to handle multiple organisations at once.
      e.g. `scope.where(provider_id: user.organisation.id).or(Trainee.where(lead_partner_id: user.organisation.school&.id))`
- [ ] Changes to trainee filtering
- [ ] Lots of other new specs...

Other areas we might need to check:
- [ ] Bulk uploads - these currently depend on the 'current organisation' of the session. What happens if there is more than one?
- [ ] Reports - similarly reports seem to depend on current organisation.
- [ ] Design work - for all the UI changes and updating the prototype

**Comment by tomtrentham** [comment]
Spike has been completed and recommendations made. This will likely be picked up in the future. Closing for now.
